classes:
  - tag
key_actions:
  27: 'exit' # esc
  61: 'plus' # =
  45: 'minus' # -
  109: 'minus' # -
  9: 'switch_next_side' # tab
  98: 'delete'  # b
  66: 'delete'  # B
  119: 'switch_prev' # w
  115: 'switch_next' # s
  87: 'switch_prev' # W
  83: 'switch_next' # S
  13: 'save' # enter
  65: 'previous' # a
  97: 'previous' # A
  100: 'pass' # d
  68: 'pass' # D

settings:
    clr: 
        - [255, 0, 0]
        - [0, 128, 0]
        - [255, 20, 147]
        - [255, 69, 0]
        - [0, 100, 0]
        - [165, 42, 42]
        - [0, 0, 255]
        - [0, 128, 128]
        - [34, 139, 34]
        - [199, 21, 133]
        - [139, 69, 19]
        - [127, 255, 212]
        - [50, 205, 50]
        - [154, 205, 50]
        - [255, 140, 0]
        - [220, 20, 60]
        - [250, 128, 114]
        - [139, 0, 0]
        - [72, 209, 204]
        - [128, 0, 0]
        - [32, 178, 178]
        - [0, 206, 209]
        - [255, 165, 0]
        - [219, 112, 147]
        - [255,233,200]
        - [122,66,23]
        - [0,0,123]
        - [123, 0, 0]
        - [233,200,255]
        - [23,66,122]
        - [0,123,0]
        - [0,123,123]
        - [123,123,0]
        - [123,0,123]
        - [0,0,0]
        - [255,255,255]
        - [255,255,0]
        - [0,255,255]
        - [255,0,255]
        - [255,0,0]
        - [0,255,0]
        - [0,0,255]
        - [255,255,255]
        - [255,255,0]
        - [0,255,255]
        - [255,0,255]
        - [255,0,0]
        - [0,255,0]
        - [0,0,255]